@interface HSAccessoryTuple
- (HMAccessory)accessory;
- (NSString)accessoryCategoryOrPrimaryServiceType;
- (NSString)titleForAccessory;
- (NSString)userFriendlyAccessoryLocalizedCapitalizedDescription;
- (NSString)userFriendlyAccessoryLocalizedLowercaseDescription;
- (id)_moveToNextStep;
- (id)description;
- (id)titleForAccessoryWithDefaultValue:(id)a3;
- (void)setAccessory:(id)a3;
@end

@implementation HSAccessoryTuple

- (id)description
{
  v3 = objc_opt_class();
  v4 = NSStringFromClass(v3);
  v5 = [(HSAccessoryTuple *)self userFriendlyAccessoryLocalizedCapitalizedDescription];
  v6 = [HSSetupContentProvider stringForHSProxCardSetupUIStep:[(HSAccessoryTuple *)self currentStep]];
  v7 = [(HSAccessoryTuple *)self accessory];
  v8 = [NSString stringWithFormat:@"%@ <accessoryCategoryOrPrimaryServiceType %@, currentStep %@, accessory %@>", v4, v5, v6, v7];

  return v8;
}

- (HMAccessory)accessory
{
  v2 = [(HSAccessoryTuple *)self configuration];
  v3 = [v2 addedAccessory];

  return v3;
}

- (void)setAccessory:(id)a3
{
  v4 = a3;
  v5 = [(HSAccessoryTuple *)self configuration];
  [v5 setAddedAccessory:v4];
}

- (NSString)accessoryCategoryOrPrimaryServiceType
{
  v3 = [(HSAccessoryTuple *)self accessory];
  v4 = [v3 hf_categoryOrPrimaryServiceType];
  v5 = v4;
  if (v4)
  {
    v6 = v4;
  }

  else
  {
    v7 = [(HSAccessoryTuple *)self configuration];
    v8 = [v7 setupDescription];
    v9 = [v8 category];
    v10 = [v9 categoryType];
    v11 = v10;
    v12 = HMAccessoryCategoryTypeOther;
    if (v10)
    {
      v12 = v10;
    }

    v6 = v12;
  }

  return v6;
}

- (NSString)userFriendlyAccessoryLocalizedCapitalizedDescription
{
  v3 = [(HSAccessoryTuple *)self accessory];
  v4 = v3;
  if (v3)
  {
    v5 = [v3 hf_userFriendlyLocalizedCapitalizedDescription];
  }

  else
  {
    v6 = [(HSAccessoryTuple *)self accessoryCategoryOrPrimaryServiceType];
    v5 = [HMAccessory hf_userFriendlyLocalizedCapitalizedDescription:v6];
  }

  return v5;
}

- (NSString)userFriendlyAccessoryLocalizedLowercaseDescription
{
  v3 = [(HSAccessoryTuple *)self accessory];
  v4 = v3;
  if (v3)
  {
    v5 = [v3 hf_userFriendlyLocalizedLowercaseDescription];
  }

  else
  {
    v6 = [(HSAccessoryTuple *)self accessoryCategoryOrPrimaryServiceType];
    v5 = [HMAccessory hf_userFriendlyLocalizedLowercaseDescription:v6];
  }

  return v5;
}

- (NSString)titleForAccessory
{
  v3 = [(HSAccessoryTuple *)self userFriendlyAccessoryLocalizedCapitalizedDescription];
  v4 = [(HSAccessoryTuple *)self titleForAccessoryWithDefaultValue:v3];

  return v4;
}

- (id)titleForAccessoryWithDefaultValue:(id)a3
{
  v4 = a3;
  v5 = [(HSAccessoryTuple *)self configuration];
  v6 = [v5 userGivenAccessoryName];

  if (v6)
  {
    v7 = [(HSAccessoryTuple *)self configuration];
    v8 = [v7 userGivenAccessoryName];
    goto LABEL_22;
  }

  v9 = [(HSAccessoryTuple *)self accessory];
  v7 = [v9 hf_primaryService];

  v10 = [(HSAccessoryTuple *)self accessory];
  v11 = [v10 configuredName];

  v12 = [v7 serviceType];
  v13 = [v12 isEqualToString:HMServiceTypeTelevision];

  if (!v13)
  {
    v14 = v11;
    if (!v11)
    {
      goto LABEL_7;
    }

    goto LABEL_10;
  }

  v14 = [v7 configuredName];

  v15 = [(HSAccessoryTuple *)self configuration];
  v16 = [v15 home];
  v17 = [v16 roomForEntireHome];
  v18 = [v17 name];

  LOBYTE(v16) = [v14 isEqualToString:v18];
  v19 = [(HSAccessoryTuple *)self configuration];
  v20 = [v19 roomName];
  v21 = [v14 isEqualToString:v20];

  if ((v16 & 1) == 0 && !v21)
  {

    if (!v14)
    {
LABEL_7:
      v22 = [(HSAccessoryTuple *)self configuration];
      v23 = [v22 setupDescription];
      v24 = [v23 hf_marketingName];
      v25 = v24;
      if (v24)
      {
        v18 = v24;
      }

      else
      {
        v33 = [(HSAccessoryTuple *)self configuration];
        v26 = [v33 setupDescription];
        v27 = [v26 accessoryName];
        v28 = v27;
        if (v27)
        {
          v18 = v27;
        }

        else
        {
          v29 = [(HSAccessoryTuple *)self accessory];
          v18 = [v29 name];
        }
      }

      goto LABEL_17;
    }

LABEL_10:
    v18 = v14;
LABEL_17:
    v30 = [HFUtilities sanitizeAutoGeneratedHomeKitName:v18];
    if ([v30 length])
    {
      v31 = v30;
    }

    else
    {
      v31 = v4;
    }

    v8 = v31;

    goto LABEL_21;
  }

  v8 = v4;
LABEL_21:

LABEL_22:

  return v8;
}

- (id)_moveToNextStep
{
  if ([(HSAccessoryTuple *)self isSetupComplete])
  {
    v3 = [NAFuture futureWithResult:&__kCFBooleanTrue];
  }

  else
  {
    v4 = [(HSAccessoryTuple *)self stateMachine];
    v5 = [(HSAccessoryTuple *)self currentStep];
    v6 = [(HSAccessoryTuple *)self configuration];
    -[HSAccessoryTuple setCurrentStep:](self, "setCurrentStep:", [v4 stepFollowingStep:v5 withConfiguration:v6]);

    v7 = [HSSetupContentProvider stringForHSProxCardSetupUIStep:[(HSAccessoryTuple *)self currentStep]];
    v8 = HFLogForCategory();
    if (os_log_type_enabled(v8, OS_LOG_TYPE_DEFAULT))
    {
      *buf = 138412290;
      v19 = v7;
      _os_log_impl(&_mh_execute_header, v8, OS_LOG_TYPE_DEFAULT, "Calculating potential skip of: %@", buf, 0xCu);
    }

    v9 = [(HSAccessoryTuple *)self stateMachine];
    v10 = [(HSAccessoryTuple *)self currentStep];
    v11 = [(HSAccessoryTuple *)self configuration];
    v12 = [v9 shouldSkipStep:v10 withConfiguration:v11];
    v15[0] = _NSConcreteStackBlock;
    v15[1] = 3221225472;
    v15[2] = sub_100063648;
    v15[3] = &unk_1000C71B0;
    v16 = v7;
    v17 = self;
    v13 = v7;
    v3 = [v12 flatMap:v15];
  }

  return v3;
}

@end