@interface CRLDrawablesAccessibilityValidator
+ (void)performPlatformSpecificValidations;
+ (void)performValidations;
@end

@implementation CRLDrawablesAccessibilityValidator

+ (void)performValidations
{
  __CRLAccessibilityValidateIsKindOfClass(@"CRLAngleGradientFill", @"CRLGradientFill");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLAngleGradientFill", @"gradientAngleInDegrees", "d", v2, v3, v4, v5, v6, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLAudioRep", @"CRLCanvasRep");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLAudioRep", @"playerController", "@", v7, v8, v9, v10, v11, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLBrushStroke", @"CRLSmartStroke");
  __CRLAccessibilityValidateIsKindOfClass(@"CRLCalligraphyStroke", @"CRLSmartStroke");
  __CRLAccessibilityValidateIvarType(@"CRLCanvas", "mInLayout", "B");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvas", @"canvasController", "@", v12, v13, v14, v15, v16, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvas", @"convertBoundsToUnscaledPoint:", "{CGPoint=dd}", v17, v18, v19, v20, v21, "{CGPoint=dd}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvas", @"convertUnscaledToBoundsRect:", "{CGRect={CGPoint=dd}{CGSize=dd}}", v22, v23, v24, v25, v26, "{CGRect={CGPoint=dd}{CGSize=dd}}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvas", @"delegate", "@", v27, v28, v29, v30, v31, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvas", @"i_registerRep:", "v", v32, v33, v34, v35, v36, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvas", @"i_unregisterRep:", "v", v37, v38, v39, v40, v41, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvas", @"layoutController", "@", v42, v43, v44, v45, v46, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvas", @"p_updateRepsFromLayouts", "B", v47, v48, v49, v50, v51, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvas", @"topLevelReps", "@", v52, v53, v54, v55, v56, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvas", @"viewScale", "d", v57, v58, v59, v60, v61, 0);
  __CRLAccessibilityValidateProtocolMethod(@"CRLCanvasEditor", @"canPerformEditorAction:withSender:", 1, 1);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasEditor", @"canvasEditorHelper", "@", v62, v63, v64, v65, v66, 0);
  __CRLAccessibilityValidateProtocolMethod(@"CRLCanvasEditor", @"canvasSelection", 1, 1);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasEditor", @"editorController", "@", v67, v68, v69, v70, v71, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasEditor", @"interactiveCanvasController", "@", v72, v73, v74, v75, v76, 0);
  __CRLAccessibilityValidateProtocolMethod(@"CRLCanvasEditor", @"canvasSelection", 1, 1);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasEditorHelper", @"canvasEditor", "@", v77, v78, v79, v80, v81, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasEditorHelper", @"delete:", "v", v82, v83, v84, v85, v86, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasEditorHelper", @"interactiveCanvasController", "@", v87, v88, v89, v90, v91, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasEditorHelper", @"keyboardMovementManipulator", "@", v92, v93, v94, v95, v96, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasEditorHelper", @"p_setLockStatusOfSelectedDrawables:", "v", v97, v98, v99, v100, v101, "B");
  __CRLAccessibilityValidateIsKindOfClass(@"CRLCanvasLayer", @"CALayer");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasView", @"canvasLayer", "@", v102, v103, v104, v105, v106, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasView", @"controller", "@", v107, v108, v109, v110, v111, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLColorFill", @"CRLFill");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLColorFill", @"color", "@", v112, v113, v114, v115, v116, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLConnectionLinePathSource", @"CRLPathSource");
  __CRLAccessibilityValidateIsKindOfClass(@"CRLConnectionLineRep", @"CRLShapeRep");
  __CRLAccessibilityValidateIsKindOfClass(@"CRLCurvedShadow", @"CRLShadow");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLBoardItemEditor", @"interactiveCanvasController", "@", v117, v118, v119, v120, v121, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"Freeform.CRLBoardItem", @"accessibilityDescription", "@", v122, v123, v124, v125, v126, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"Freeform.CRLBoardItemSelection", @"CRLSubselection");
  __CRLAccessibilityValidateIsKindOfClass(@"CRLDropShadow", @"CRLShadow");
  __CRLAccessibilityValidateProtocolMethod(@"CRLEditor", @"canPerformEditorAction:withSender:", 0, 1);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLEditorController", @"currentEditors", "@", v127, v128, v129, v130, v131, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLEditorController", @"editorForEditAction:withSender:", "@", v132, v133, v134, v135, v136, ":");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLEditorController", @"mostSpecificCurrentEditorOfClass:", "@", v137, v138, v139, v140, v141, "#");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLEditorController", @"selectionPath", "@", v142, v143, v144, v145, v146, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLEditorController", @"setSelectionPath:", "v", v147, v148, v149, v150, v151, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLEditorController", @"textInputEditor", "@", v152, v153, v154, v155, v156, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLFill", @"fillType", "q", v157, v158, v159, v160, v161, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLFill", @"referenceColor", "@", v162, v163, v164, v165, v166, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLGradientFill", @"CRLFill");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLGradientFill", @"gradientStops", "@", v167, v168, v169, v170, v171, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLGradientFill", @"gradientType", "Q", v172, v173, v174, v175, v176, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLGradientFillStop", @"color", "@", v177, v178, v179, v180, v181, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLGroupRep", @"p_allowedToEditChildren", "B", v182, v183, v184, v185, v186, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLImageFill", @"CRLFill");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLImageFill", @"technique", "Q", v187, v188, v189, v190, v191, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLImageFill", @"tintColor", "@", v192, v193, v194, v195, v196, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"Freeform.CRLImageItem", @"Freeform.CRLBoardItem");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLImageLayout", @"isInMaskEditMode", "B", v197, v198, v199, v200, v201, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLImageLayout", @"maskLayout", "@", v202, v203, v204, v205, v206, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLImageLayout", @"CRLMediaLayout");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLImageRep", @"editMaskWithHUD:", "v", v207, v208, v209, v210, v211, "B");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLImageRep", @"imageInfo", "@", v212, v213, v214, v215, v216, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLImageRep", @"imageLayout", "@", v217, v218, v219, v220, v221, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLImageRep", @"p_allowedToEditMask", "B", v222, v223, v224, v225, v226, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLImageRep", @"CRLCanvasRep");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasInfoGeometry", @"angle", "d", v227, v228, v229, v230, v231, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasInfoGeometry", @"position", "{CGPoint=dd}", v232, v233, v234, v235, v236, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasInfoGeometry", @"size", "{CGSize=dd}", v237, v238, v239, v240, v241, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"addCommonObservers", "v", v242, v243, v244, v245, v246, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"canvas", "@", v247, v248, v249, v250, v251, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"canvasEditor", "@", v252, v253, v254, v255, v256, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"canvasView", "@", v257, v258, v259, v260, v261, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"collaboratorCursorDelegate", "@", v262, v263, v264, v265, v266, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"convertBoundsToUnscaledPoint:", "{CGPoint=dd}", v267, v268, v269, v270, v271, "{CGPoint=dd}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"convertBoundsToUnscaledRect:", "{CGRect={CGPoint=dd}{CGSize=dd}}", v272, v273, v274, v275, v276, "{CGRect={CGPoint=dd}{CGSize=dd}}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"convertUnscaledToBoundsPoint:", "{CGPoint=dd}", v277, v278, v279, v280, v281, "{CGPoint=dd}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"convertUnscaledToBoundsRect:", "{CGRect={CGPoint=dd}{CGSize=dd}}", v282, v283, v284, v285, v286, "{CGRect={CGPoint=dd}{CGSize=dd}}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"delegate", "@", v287, v288, v289, v290, v291, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"editorController", "@", v292, v293, v294, v295, v296, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"endEditing", "v", v297, v298, v299, v300, v301, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"hitRep:", "@", v302, v303, v304, v305, v306, "{CGPoint=dd}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"documentIsSharedReadOnly", "B", v307, v308, v309, v310, v311, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"infosForCurrentSelectionPath", "@", v312, v313, v314, v315, v316, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"infosForSelectionPath:", "@", v317, v318, v319, v320, v321, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"infosToDisplay", "@", v322, v323, v324, v325, v326, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"layerHost", "@", v327, v328, v329, v330, v331, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"layoutsForSelectionPath:", "@", v332, v333, v334, v335, v336, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"p_repsForCollaboratorCursorSelectionPath:", "@", v337, v338, v339, v340, v341, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"removeCommonObservers", "v", v342, v343, v344, v345, v346, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"repForInfo:", "@", v347, v348, v349, v350, v351, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"repForLayout:", "@", v352, v353, v354, v355, v356, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"repsForInfo:", "@", v357, v358, v359, v360, v361, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"scrollCurrentSelectionToVisibleWithOptions:", "v", v362, v363, v364, v365, v366, "Q");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"scrollToCollaborator:withSelectionPath:", "v", v367, v368, v369, v370, v371, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"scrollToSelectionPath:scrollOptions:", "v", v372, v373, v374, v375, v376, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"teardown", "v", v377, v378, v379, v380, v381, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"topLevelRepsForHitTesting", "@", v382, v383, v384, v385, v386, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"collaboratorCursorSelectionPathChangedFromSelectionPath:toSelectionPath:collaboratorPresence:", "v", v387, v388, v389, v390, v391, "@");
  __CRLAccessibilityValidateIvarType(@"CRLKeyboardMovementManipulator", "mICC", "CRLInteractiveCanvasController");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLKeyboardMovementManipulator", @"moveSelectionByDelta:", "v", v392, v393, v394, v395, v396, "{CGPoint=dd}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasKnobTracker", @"beginMovingKnob", "v", v397, v398, v399, v400, v401, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasKnobTracker", @"currentBoundsForStandardKnobs", "{CGRect={CGPoint=dd}{CGSize=dd}}", v402, v403, v404, v405, v406, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasKnobTracker", @"endMovingKnob", "v", v407, v408, v409, v410, v411, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasKnobTracker", @"initWithRep:knob:", "@", v412, v413, v414, v415, v416, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasKnobTracker", @"knob", "@", v417, v418, v419, v420, v421, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasKnobTracker", @"moveKnobToRepPosition:", "v", v422, v423, v424, v425, v426, "{CGPoint=dd}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasKnobTracker", @"setDidDrag:", "v", v427, v428, v429, v430, v431, "B");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasLayout", @"dragBy:", "v", v432, v433, v434, v435, v436, "{CGPoint=dd}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasLayout", @"info", "@", v437, v438, v439, v440, v441, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasLayout", @"inspectorGeometry", "@", v442, v443, v444, v445, v446, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasLayout", @"invalidate", "v", v447, v448, v449, v450, v451, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasLayout", @"isDraggable", "B", v452, v453, v454, v455, v456, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasLayout", @"isSelectable", "B", v457, v458, v459, v460, v461, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasLayout", @"layoutController", "@", v462, v463, v464, v465, v466, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasLayoutController", @"canvas", "@", v467, v468, v469, v470, v471, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasLayoutController", @"rootLayout", "@", v472, v473, v474, v475, v476, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasLayoutGeometry", @"frame", "{CGRect={CGPoint=dd}{CGSize=dd}}", v477, v478, v479, v480, v481, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasLayoutGeometry", @"transform", "{CGAffineTransform=dddddd}", v482, v483, v484, v485, v486, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"Freeform.CRLShapeItem", @"headLineEnd", "@", v487, v488, v489, v490, v491, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"Freeform.CRLShapeItem", @"stroke", "@", v492, v493, v494, v495, v496, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"Freeform.CRLShapeItem", @"tailLineEnd", "@", v497, v498, v499, v500, v501, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"Freeform.CRLMovieItem", @"Freeform.CRLBoardItem");
  __CRLAccessibilityValidateIsKindOfClass(@"CRLMovieKnob", @"CRLCanvasKnob");
  __CRLAccessibilityValidateIsKindOfClass(@"CRLMovieRep", @"CRLCanvasRep");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLMovieRep", @"isPlayable", "B", v502, v503, v504, v505, v506, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLMovieRep", @"i_togglePlayPauseTriggeredFromKnob", "v", v507, v508, v509, v510, v511, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLMovieRep", @"playerController", "@", v512, v513, v514, v515, v516, 0);
  __CRLAccessibilityValidateClassMethod(@"CRLPathSource", @"pathSourceForShapeType:naturalSize:");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLPathSource", @"copyWithZone:", "@", v517, v518, v519, v520, v521, "^{_NSZone=}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLPathSource", @"isCircular", "B", v522, v523, v524, v525, v526, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLPathSource", @"isRectangular", "B", v527, v528, v529, v530, v531, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLPathSource", @"naturalSize", "{CGSize=dd}", v532, v533, v534, v535, v536, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"becameNotSelected", "v", v537, v538, v539, v540, v541, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"becameSelected", "v", v542, v543, v544, v545, v546, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"canvas", "@", v547, v548, v549, v550, v551, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"convertNaturalPointFromUnscaledCanvas:", "{CGPoint=dd}", v552, v553, v554, v555, v556, "{CGPoint=dd}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"convertNaturalRectFromUnscaledCanvas:", "{CGRect={CGPoint=dd}{CGSize=dd}}", v557, v558, v559, v560, v561, "{CGRect={CGPoint=dd}{CGSize=dd}}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"convertNaturalPointToUnscaledCanvas:", "{CGPoint=dd}", v562, v563, v564, v565, v566, "{CGPoint=dd}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"convertNaturalRectToUnscaledCanvas:", "{CGRect={CGPoint=dd}{CGSize=dd}}", v567, v568, v569, v570, v571, "{CGRect={CGPoint=dd}{CGSize=dd}}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"dynamicOperationDidEnd", "v", v572, v573, v574, v575, v576, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"frameInScreenSpace", "{CGRect={CGPoint=dd}{CGSize=dd}}", v577, v578, v579, v580, v581, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"frameInUnscaledCanvas", "{CGRect={CGPoint=dd}{CGSize=dd}}", v582, v583, v584, v585, v586, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"handleSingleTapAtPoint:inputType:", "B", v587, v588, v589, v590, v591, "{CGPoint=dd}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"handleDoubleTapAtPoint:inputType:", "B", v592, v593, v594, v595, v596, "{CGPoint=dd}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"i_willBeRemoved", "v", v597, v598, v599, v600, v601, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"info", "@", v602, v603, v604, v605, v606, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"invalidateKnobs", "v", v607, v608, v609, v610, v611, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"isLocked", "B", v612, v613, v614, v615, v616, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"isSelected", "B", v617, v618, v619, v620, v621, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"isSelectedIgnoringLocking", "B", v622, v623, v624, v625, v626, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"layerFrameInScaledCanvas", "{CGRect={CGPoint=dd}{CGSize=dd}}", v627, v628, v629, v630, v631, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"layout", "@", v632, v633, v634, v635, v636, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"knobForTag:", "@", v637, v638, v639, v640, v641, "Q");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"knobs", "@", v642, v643, v644, v645, v646, 0);
  __CRLAccessibilityValidateIvarType(@"CRLCanvasRep", "mKnobs", "NSArray");
  __CRLAccessibilityValidateIvarType(@"CRLCanvasRep", "mKnobsAreShowing", "B");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"naturalBounds", "{CGRect={CGPoint=dd}{CGSize=dd}}", v647, v648, v649, v650, v651, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"newTrackerForKnob:", "@", v652, v653, v654, v655, v656, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"parentRep", "@", v657, v658, v659, v660, v661, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"repForSelecting", "@", v662, v663, v664, v665, v666, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"shouldCreateKnobs", "B", v667, v668, v669, v670, v671, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"transformToConvertNaturalFromLayerRelative", "{CGAffineTransform=dddddd}", v672, v673, v674, v675, v676, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"collaboratorCursorChangedToSelectionPath", "v", v677, v678, v679, v680, v681, "@");
  __CRLAccessibilityValidateIsKindOfClass(@"CRLResizeKnobTracker", @"CRLCanvasKnobTracker");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLResizeKnobTracker", @"p_updateHUD", "v", v682, v683, v684, v685, v686, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLScalarPathSource", @"type", "Q", v687, v688, v689, v690, v691, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLScalarPathSource", @"scalar", "d", v692, v693, v694, v695, v696, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLScalarPathSource", @"CRLPathSource");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLShadow", @"color", "@", v697, v698, v699, v700, v701, 0);
  __CRLAccessibilityValidateIvarType(@"CRLShadow", "mAngle", "d");
  __CRLAccessibilityValidateIvarType(@"CRLShadow", "mEnabled", "B");
  __CRLAccessibilityValidateInstanceMethodComplete(@"Freeform.CRLShapeItem", @"pathSource", "@", v702, v703, v704, v705, v706, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLShapeControlKnobTracker", @"p_updateHUDAtPoint:", "v", v707, v708, v709, v710, v711, "{CGPoint=dd}");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLShapeControlKnobTracker", @"endMovingKnob", "v", v712, v713, v714, v715, v716, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLShapeLayout", @"CRLCanvasLayout");
  __CRLAccessibilityValidateIsKindOfClass(@"CRLShapeRep", @"CRLCanvasRep");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLShapeRep", @"shapeInfo", "@", v717, v718, v719, v720, v721, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLShapeRep", @"shapeLayout", "@", v722, v723, v724, v725, v726, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLShapeEditor", @"selectedObjectsSupportingEndpoints", "@", v727, v728, v729, v730, v731, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLSmartStroke", @"strokeName", "@", v732, v733, v734, v735, v736, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLSmartStroke", @"CRLStroke");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLStroke", @"color", "@", v737, v738, v739, v740, v741, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLStroke", @"pattern", "@", v742, v743, v744, v745, v746, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLStroke", @"isNullStroke", "B", v747, v748, v749, v750, v751, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLStroke", @"width", "d", v752, v753, v754, v755, v756, 0);
  __CRLAccessibilityValidateProtocolMethod(@"CRLStrokeEditor", @"stroke", 1, 1);
  __CRLAccessibilityValidateClassMethod(@"CRLStrokePattern", @"solidPattern");
  __CRLAccessibilityValidateClassMethod(@"CRLStrokePattern", @"emptyPattern");
  __CRLAccessibilityValidateClassMethod(@"CRLStrokePattern", @"shortDashPattern");
  __CRLAccessibilityValidateClassMethod(@"CRLStrokePattern", @"mediumDashPattern");
  __CRLAccessibilityValidateClassMethod(@"CRLStrokePattern", @"longDashPattern");
  __CRLAccessibilityValidateClassMethod(@"CRLStrokePattern", @"roundDashPattern");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLStrokePattern", @"patternType", "q", v757, v758, v759, v760, v761, 0);
}

+ (void)performPlatformSpecificValidations
{
  __CRLAccessibilityValidateIsKindOfClass(@"CRLiOSCheckableTableViewCell", @"UITableViewCell");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSCheckableTableViewCell", @"checked", "B", v2, v3, v4, v5, v6, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSCheckableTableViewCell", @"setChecked:", "v", v7, v8, v9, v10, v11, "B");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSCheckableTableViewCell", @"setImage:forState:", "v", v12, v13, v14, v15, v16, "@");
  __CRLAccessibilityValidateIsKindOfClass(@"CRLiOSDisclosureTableViewCell", @"UITableViewCell");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSDisclosureTableViewCell", @"nextLevelController", "@", v17, v18, v19, v20, v21, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSDoubleSegmentedControlTableViewCell", @"leftSegmentedControl", "@", v22, v23, v24, v25, v26, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSDoubleSegmentedControlTableViewCell", @"rightSegmentedControl", "@", v27, v28, v29, v30, v31, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"textInputResponder", "@", v32, v33, v34, v35, v36, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLiOSCanvasViewController", @"UIViewController");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSCanvasViewController", @"delegate", "@", v37, v38, v39, v40, v41, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSCanvasViewController", @"interactiveCanvasController", "@", v42, v43, v44, v45, v46, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSCanvasViewController", @"p_buildMenuItems:forSelectionPath:", "v", v47, v48, v49, v50, v51, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSCanvasViewController", @"p_buildMenuTitles:forSelectionPath:", "v", v52, v53, v54, v55, v56, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSCanvasViewController", @"asiOSCVC", "@", v57, v58, v59, v60, v61, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSCanvasViewController", @"delegate", "@", v62, v63, v64, v65, v66, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSCanvasViewController", @"interactiveCanvasController", "@", v67, v68, v69, v70, v71, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSCanvasViewController", @"setContextMenuMightBeDisplayed:", "v", v72, v73, v74, v75, v76, "B");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSCanvasViewController", @"showEditMenuForSelectionPath:", "v", v77, v78, v79, v80, v81, "@");
  __CRLAccessibilityValidateProtocolMethod(@"CRLMultiPaneSubpane", @"paneIcon", 0, 1);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSSegmentedControlTableViewCell", @"segmentedControl", "@", v82, v83, v84, v85, v86, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLiOSSwitchTableViewCell", @"CRLiOSInspectorTableViewCell");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSSwitchTableViewCell", @"switchView", "@", v87, v88, v89, v90, v91, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLiOSSwitchTableViewCell", @"title", "@", v92, v93, v94, v95, v96, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"Freeform.CRLTextInputResponder", @"UIResponder");
  __CRLAccessibilityValidateInstanceMethodComplete(@"Freeform.CRLTextInputResponder", @"editor", "@", v97, v98, v99, v100, v101, 0);
  __CRLAccessibilityValidateIsKindOfClass(@"CRLiOSTickedSlider", @"UISlider");
  __CRLAccessibilityValidateClass(@"CRLShapeLayout");
  __CRLAccessibilityValidateClass(@"CRLStroke");
  __CRLAccessibilityValidateInstanceMethod(@"CRLInteractiveCanvasController", @"setViewScale:andScrollViewFrame:maintainPosition:animated:");
  __CRLAccessibilityValidateInstanceMethod(@"CRLiOSImageHUDViewController", @"loadView");
  __CRLAccessibilityValidateInstanceMethod(@"CRLCanvasKnob", @"knobImage");
  __CRLAccessibilityValidateInstanceMethod(@"CRLCanvasRep", @"dynamicDragDidBegin");
  __CRLAccessibilityValidateInstanceMethod(@"CRLCanvasRep", @"setParentRep:");
  __CRLAccessibilityValidateInstanceMethod(@"CRLResizeKnobTracker", @"currentBoundsForStandardKnobs");
  __CRLAccessibilityValidateInstanceMethod(@"CRLiOSSegmentedControlTableViewCell", @"segmentedControl");
  __CRLAccessibilityValidateInstanceMethod(@"CRLShapeLayout", @"layoutInfoGeometry");
  __CRLAccessibilityValidateInstanceMethod(@"CRLStroke", @"pattern");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLGroupRep", @"childReps", "@", v102, v103, v104, v105, v106, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLGroupRep", @"childRepsForHitTesting", "@", v107, v108, v109, v110, v111, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLInteractiveCanvasController", @"scrollView:willAnimateToContentOffset:", "v", v112, v113, v114, v115, v116, "@");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvasRep", @"initWithLayout:canvas:", "@", v117, v118, v119, v120, v121, "@");
  __CRLAccessibilityValidateIsKindOfClass(@"CRLGroupRep", @"CRLCanvasRep");
  __CRLAccessibilityValidateIvar(@"CRLCanvas", "mAllReps");
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvas", @"crlaxPreventReloadingChildren", "v", v122, v123, v124, v125, v126, 0);
  __CRLAccessibilityValidateInstanceMethodComplete(@"CRLCanvas", @"crlaxRevertReloadingChildrenTo:andReloadForChanges:", "v", v127, v128, v129, v130, v131, "B");
}

@end